import { cp,mkdtemp,readFile,writeFile,mkdir,rm,symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join,resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
const root=resolve(import.meta.dirname,'..'),out=join(root,'docs/acceptance/mutations');await mkdir(out,{recursive:true});
const cases=[
  {id:'M33-target-search-200',file:'src/library/service.js',from:"packageName.length<=200,'TARGET_SEARCH_UNSUPPORTED'",to:"packageName.length<=214,'TARGET_SEARCH_UNSUPPORTED' /* MUTATION: unsupported searches are accepted */",test:'tests/library-target.test.mjs',pattern:'^P06A-T01/T02/T03',reason:/ERR_ASSERTION/},
  {id:'M34-target-validation-first',file:'src/library/service.js',from:"const packageName=input.packageName;\n      requireCondition(text(packageName,214)&&PACKAGE_NAME.test(packageName),'INVALID_INPUT','packageName is invalid.');",to:"const packageName=input.packageName;\n      requireCondition(text(packageName,214),'INVALID_INPUT','packageName is invalid.'); /* MUTATION: invalid names reach support check */",test:'tests/library-target.test.mjs',pattern:'^P06A-T01/T02/T03',reason:/ERR_ASSERTION/},
  {id:'M35-target-exact-result',file:'src/client-ui.js',from:"item.package?.registry==='npm'&&item.package?.name===target?.packageName",to:"item.package?.name?.includes(target?.packageName) /* MUTATION: substring matches are highlighted */",test:'tests/client-target.test.mjs',pattern:'^P06A-T08/T09/T10b',reason:/ERR_ASSERTION/},
  {id:'M36-target-consume-id',file:'src/library/service.js',from:"if(target?.targetId!==input.targetId)return{consumed:false};",to:"if(target?.targetId===input.targetId)return{consumed:false}; /* MUTATION: stale ID clears new target */",test:'tests/library-target.test.mjs',pattern:'^P06A-T01/T02/T03',reason:/ERR_ASSERTION/},
  {id:'M37-active-view-target-card-hidden',file:'src/client-ui.js',from:"targetState==='found'?h('div',{className:'hm-library-grid'},...items.filter(exact).map(card)):null,",to:"targetState==='found'?null:null, /* MUTATION: active view consumes target while exact cards are hidden */",test:'tests/client-target.test.mjs',pattern:'^P06A-T11:',reason:/ERR_ASSERTION/},
  {id:'M38-seat-target-overlay-suppressed',file:'src/client-ui.js',from:'if(!embedded)setLibraryVisible(true);',to:'if(!embedded&&entryVisible)setLibraryVisible(true); /* MUTATION: the panel seat blocks OS target presentation */',test:'tests/client-target.test.mjs',pattern:'^P06A-T13:',reason:/ERR_ASSERTION/},
  {id:'M39-seat-takeover-closes-view',file:'src/client-ui.js',from:'const setEntryVisible=value=>{entryVisible=value;for(const listener of entryListeners)listener(value);};',to:'const setEntryVisible=value=>{entryVisible=value;if(!value)setLibraryVisible(false);for(const listener of entryListeners)listener(value);}; /* MUTATION: seat takeover closes a foreground view */',test:'tests/client-target.test.mjs',pattern:'^P06A-T11/T13:',reason:/ERR_ASSERTION/},
  {id:'M40-same-name-target-id-skips-reload',file:'src/client-ui.js',from:'[visible,load,target?.targetId,targetGeneration]',to:'[visible,load,targetGeneration] /* MUTATION: same-name target identity does not refetch the catalog */',test:'tests/client-target.test.mjs',pattern:'^P06A-T11/T13: a new target ID',reason:/ERR_ASSERTION/},
  {id:'M41-embedded-target-owner-lost',file:'src/client-ui.js',from:"if(embedded||embeddedSurfaceCount===0){\n            const current=(await request('/hanamesh/library/target')).target;\n            if(stopped)return;\n            if(embedded||embeddedSurfaceCount===0){",to:"if(true){ /* MUTATION: background overlay competes with embedded Market */\n            const current=(await request('/hanamesh/library/target')).target;\n            if(stopped)return;\n            if(true){",test:'tests/client-target.test.mjs',pattern:'^P06A-T13: an already mounted embedded Market',reason:/ERR_ASSERTION/},
  {id:'M42-late-overlay-catalog-paints-target',file:'src/client-ui.js',from:'if(sequence!==loadSequence.current||(!embedded&&embeddedSurfaceCount>0))return;',to:'if(sequence!==loadSequence.current)return; /* MUTATION: stale overlay catalog response paints target cards */',test:'tests/client-target.test.mjs',pattern:'^P06A-T13: embedded Market takes ownership while an overlay catalog response is delayed',reason:/ERR_ASSERTION/},
  {id:'M43-overlay-status-after-seat-change',file:'src/client-ui.js',from:'!target||!visible||(!embedded&&embeddedSurfaceCount>0)?null:',to:'!target||!visible?null: /* MUTATION: stale overlay status appears after embedded mount */',test:'tests/client-target.test.mjs',pattern:'^P06A-T13: an overlay effect queued before embedded mount',reason:/ERR_ASSERTION/},
  {id:'M44-stale-overlay-effect-consumes',file:'src/client-ui.js',from:'if(!targetState||!target||(!embedded&&embeddedSurfaceCount>0)||consumedTargetId.current===target.targetId)return;',to:'if(!targetState||!target||consumedTargetId.current===target.targetId)return; /* MUTATION: queued overlay effect consumes after embedded mount */',test:'tests/client-target.test.mjs',pattern:'^P06A-T13: an overlay effect queued before embedded mount',reason:/ERR_ASSERTION/},
  {id:'M45-embedded-unmount-never-reacquires',file:'src/client-ui.js',from:'const ownerResumed=!embedded&&lastOwnedEpoch!==embeddedSurfaceEpoch;',to:'const ownerResumed=false; /* MUTATION: the pending same-ID target is ignored after embedded unmount */',test:'tests/client-target.test.mjs',pattern:'^P06A-T13: an unconsumed target returns to the overlay',reason:/ERR_ASSERTION/},
  {id:'M46-owner-resume-does-not-reload',file:'src/client-ui.js',from:'[visible,load,target?.targetId,targetGeneration]',to:'[visible,load,target?.targetId] /* MUTATION: same-ID owner handoff does not reload catalog */',test:'tests/client-target.test.mjs',pattern:'^P06A-T13: an unconsumed target returns to the overlay',reason:/ERR_ASSERTION/},
  {id:'M21-market-close-retry-rejected-cache',file:'src/client-ui.js',from:'catch(error=>{closeTask=undefined;throw error;})',to:'catch(error=>{throw error;}) /* MUTATION: failed close is cached forever */',test:'tests/client-heartbeat.test.mjs',pattern:'^AH-VL10:',reason:/network recovery allows a new explicit close request/},
  {id:'M22-market-late-open-orphan',file:'src/client-ui.js',from:'if(mounted.current&&surfaceVisible.current&&surfaceEpoch.current===epoch)return false;',to:'return false; /* MUTATION: late Open receipt is never released */',test:'tests/client-heartbeat.test.mjs',pattern:'^AH-VL13:',reason:/unmounted consumer closes late exact receipt/},
  {id:'M19-market-view-heartbeat-missing',file:'src/client-ui.js',from:'if(closed||renewing)return;\n      renewing=true;clearTimeout(timer);',to:'return; /* MUTATION: visible view never renews */\n      renewing=true;clearTimeout(timer);',test:'tests/client-heartbeat.test.mjs',pattern:'^AH-VL01:',reason:/visible idle view must consume heartbeat before the 90s lease expires/},
  {id:'M20-market-view-cleanup-missing',file:'src/client-ui.js',from:"return closeTask??=request('/apps/close',{method:'POST',body:JSON.stringify(lease),keepalive:true}).catch(error=>{closeTask=undefined;throw error;});",to:'return closeTask??=Promise.resolve(); /* MUTATION: cleanup cancels timers but never releases lease */',test:'tests/client-heartbeat.test.mjs',pattern:'^AH-VL03:',reason:/hidden overlay explicitly releases its lease/},
  {id:'M18-reclaim-spawn-budget',file:'src/runtime.js',from:"await bounded(Promise.race([ownershipReady, spawned]), 5_000 + config.stopGraceMs + 2_000, 'Runtime ownership recovery');",to:"await bounded(spawned, 5_000, 'Process spawn'); /* MUTATION: old reclaim competes with new spawn budget */",test:'tests/reclaim-spawn.test.mjs',pattern:'^AH-L07:',reason:/proven orphan reclaim followed by launch must succeed/},
  {id:'M01-single-instance',file:'src/manager.js',from:'const reuse = app.singleInstanceOnly;',to:'const reuse = false;',test:'tests/manager.test.mjs',pattern:'^H02:',reason:/every concurrent open of a single-instance app joins the one reservation/},
  {id:'M02-reserve-launch',file:'src/consistency.js',from:"await publish(); // ORDER:RESERVE\n  await checkpoint('reservation-durable');\n  return await launch(); // ORDER:LAUNCH",to:"await launch(); // MUTATION: unsafe launch before ownership\n  await checkpoint('reservation-durable');\n  return await publish();",test:'tests/crash.test.mjs',pattern:'^X03 reserve-launch:',reason:/RESERVE_BOUNDARY_UNSAFE/},
  {id:'M03-stop-publish',file:'src/consistency.js',from:"await stop(); // ORDER:STOP\n  await checkpoint('runtime-stopped');\n  return await publish(); // ORDER:STOPPED-PUBLISH",to:"await publish(); // MUTATION: unsafe acknowledgement before termination\n  await checkpoint('runtime-stopped');\n  return await stop();",test:'tests/crash.test.mjs',pattern:'^X03 stop-publish:',reason:/STOP_BOUNDARY_UNSAFE/},
  {id:'M05-credential-declared-only',file:'src/manager.js',from:"if (envNames.has(key) && typeof value === 'string' && !value.includes('\\0')) env[key] = value; else rejected.push(key);",to:"env[key] = value; /* MUTATION: undeclared credential names leak into the child */",test:'tests/credentials.test.mjs',pattern:'^AH-C2',reason:/Expected values to be strictly equal|UNDECLARED_KEY/},
  {id:'M04-socket-ownership',file:'src/runtime.js',from:"runtime?.mode !== 'owned' || await ownsLoopbackPort(runtime.groupId, Number(new URL(origin).port))",to:'true /* MUTATION: accepts unrelated same-marker HTTP endpoint */',test:'tests/storage.test.mjs',pattern:'^AH readiness:',reason:/Missing expected rejection/},
  {id:'M06-router-sets-declared',file:'src/router/broker.js',from:"if(byId.has('env:'+name)){const expanded=template(value,vars);if(expanded)env[name]=expanded;}",to:"if(true){const expanded=template(value,vars);if(expanded)env[name]=expanded;} /* MUTATION: undeclared sets target */",test:'tests/router-broker.test.mjs',pattern:'^AH-R11/AK11',reason:/NOT_DECLARED|Expected values to be strictly deep-equal|actual/},
  {id:'M07-runtime-exec-traversal',file:'src/descriptor.js',from:"typeof exec === 'string' && safeRelativePosix(exec)",to:"typeof exec === 'string' && exec.length > 0 /* MUTATION: runtime exec traversal accepted */",test:'tests/descriptor-runtime.test.mjs',pattern:'^AH-P02:',reason:/Missing expected exception|INVALID_RUNTIME/},
  {id:'M09-runtime-lock-unproven-orphan',file:'src/store.js',from:"unknown.push({ pid: child.pid, role: child.role ?? null, command: live.command ?? null });",to:"continue; /* MUTATION: a live child that cannot be proven ours is treated as gone and the lock is taken over it */",test:'tests/runtime-lock.test.mjs',pattern:'^AH-L04:',reason:/Missing expected rejection|DATA_ROOT_BUSY/},
  {id:'M10-library-node-electron',file:'src/library/locate.js',from:"if(versions.electron!==undefined)return undefined;",to:"if(false)return undefined; /* MUTATION: an Electron host silently runs library installs with its own executable */",test:'tests/library-locate.test.mjs',pattern:'^AH-L09:',reason:/Expected values to be strictly equal|NODE_RUNTIME_REQUIRED/},
  {id:'M11-usage-denied-counts',file:'src/gateway.js',from:"if (response.statusCode !== 401 && response.statusCode !== 403) this.#forwarded();",to:"this.#forwarded(); /* MUTATION: an app's own 401/403 answer counts as usage */",test:'tests/usage-evidence.test.mjs',pattern:'^AH-U02:',reason:/Expected values to be strictly equal|strictly deep-equal/},
  {id:'M12-usage-hour-bucket',file:'src/router/receipts.js',from:"if (!includeCurrent && item.hour >= current) continue;",to:"if (false) continue; /* MUTATION: the running hour is reported before its count is final (every request could become a use event) */",test:'tests/usage-evidence.test.mjs',pattern:'^AH-U02:',reason:/the running hour is not reported yet|Expected values to be strictly equal|strictly deep-equal/},
  {id:'M15-receipt-count-not-accumulated',file:'src/router/receipts.js',from:"item[field] += 1; item.firstAt = Math.min(item.firstAt, at);",to:"item[field] = 1; item.firstAt = Math.min(item.firstAt, at); /* MUTATION: a receipt never counts past one request */",test:'tests/usage-evidence.test.mjs',pattern:'^AH-U08',reason:/Expected values to be strictly equal|strictly deep-equal/},
  {id:'M16-router-inject-observer-blocks-launch',file:'src/router/broker.js',from:"if(routes.length){try{onInject({appId,instanceId,routes});}catch{}}",to:"if(routes.length){onInject({appId,instanceId,routes});} /* MUTATION: a failing receipt observer fails the credential injection */",test:'tests/router-broker.test.mjs',pattern:'^AH-R12',reason:/a throwing receipt observer never fails the credential injection/},
  {id:'M13-market-suite-protected',file:'src/library/install.js',from:"const blocked=new Set(PROTECTED_PACKAGES);",to:"const blocked=new Set(); /* MUTATION: the market may remove hanamesh-core / app-host itself */",test:'tests/library-market.test.mjs',pattern:'^AH-M02:',reason:/Missing expected rejection|PACKAGE_DENIED/},
  {id:'M14-provision-input-400',file:'src/library/service.js',from:"requireCondition(text(input?.runtimeItem,160),'INVALID_INPUT','runtimeItem is required.');",to:"requireCondition(true,'INVALID_INPUT','runtimeItem is required.'); /* MUTATION: a missing runtimeItem starts the operation and fails inside it (LIB-PROVISION-INPUT) */",test:'tests/library-market.test.mjs',pattern:'^AH-M06',reason:/Missing expected rejection|INVALID_INPUT/},
  {id:'M17-market-seat-exclusive',file:'src/client-ui.js',from:"const conflict=marketSeatTaken(ctx)||await dshmarketInstalled();",to:"const conflict=false; /* MUTATION: the market seat is taken even when dshmarket already holds or owns it */",test:'tests/market-seat.test.mjs',pattern:'^AH-MS0[23]',reason:/the seat is never contested|a registered seat is never overwritten/},
  {id:'M08-node-runtime-electron',file:'src/runtime.js',from:"if (process.versions.electron !== undefined) {\n      throw new AppHostError('NODE_RUNTIME_REQUIRED', 'Electron hosts must configure an external Node.js executable.');\n    }",to:"if (process.versions.electron !== undefined) {\n      selected = process.execPath; /* MUTATION: Electron silently self-hosts instead of failing closed */\n    }",test:'tests/node-runtime.test.mjs',pattern:'^AH-K5-2: Electron self-hosting',reason:/Missing expected rejection|NODE_RUNTIME_REQUIRED/},
  {id:'M23-unregister-ignores-registration-identity',file:'src/manager.js',from:"if (current !== registrationId) return",to:"if (!current) return /* MUTATION: a stale disposer may drop a newer registration */",test:'tests/app-package-lifecycle.test.mjs',pattern:'^AH-PK(06|11) ',reason:/Expected values to be strictly deep-equal|registration-replaced/},
  {id:'M24-unregister-orphans-runtime',file:'src/manager.js',from:"try { pending.push((await this.#stopStep(i.id,true,i.principalId)).task); }",to:"try { /* MUTATION: an uninstalled app keeps its owned runtime */ }",test:'tests/app-package-lifecycle.test.mjs',pattern:'^AH-PK04 ',reason:/Expected values to be strictly equal|stopped/},
  {id:'M25-installed-lifecycle-always-optional',file:'src/library/installed.js',from:"hostLifecycle:contractVersion>=2?'host-optional':'host-required'",to:"hostLifecycle:'host-optional' /* MUTATION: v1 packages are not flagged */",test:'tests/library-installed.test.mjs',pattern:'^AH-L13 ',reason:/Expected values to be strictly deep-equal/},
  {id:'M26-entry-check-accepts-required-inject',file:'src/app-package.js',from:"requireCondition(!names.includes('hanameshApps'), 'APP_PACKAGE_HOST_REQUIRED',",to:"requireCondition(true, 'APP_PACKAGE_HOST_REQUIRED', /* MUTATION: v1 entry passes the v2 check */",test:'tests/app-package-lifecycle.test.mjs',pattern:'^AH-PK07 ',reason:/Missing expected exception|APP_PACKAGE_HOST_REQUIRED/},
  {id:'M27-queued-open-skips-registration-check',file:'src/manager.js',from:"requireCondition(this.#definitions.get(app.id) === app,'APP_NOT_REGISTERED','Application is not registered.',{},404);",to:"/* MUTATION: a queued Open reserves for an app unregistered meanwhile */",test:'tests/app-package-lifecycle.test.mjs',pattern:'^AH-PK08 ',reason:/APP_NOT_REGISTERED|Expected values to be strictly/},
  {id:'M28-unregister-targets-outside-queue',file:'src/manager.js',from:"const tasks = await this.#queue.run(async () => {",to:"const tasks = await (step => step())(async () => { /* MUTATION: targets read outside the serial queue miss a reservation still committing */",test:'tests/app-package-lifecycle.test.mjs',pattern:'^AH-PK10 ',reason:/Expected values to be strictly|stopped/},
  {id:'M30-registration-id-from-content-hash',file:'src/manager.js',from:"const registrationId = randomUUID();",to:"const registrationId = fingerprint(d).replace(/^(.{8})(.{4}).(.{3}).(.{3})(.{12}).*$/,'$1-$2-4$3-8$4-$5'); /* MUTATION: registration identity falls back to the content fingerprint (UUID-shaped) */",test:'tests/app-package-lifecycle.test.mjs',pattern:'^AH-PK(06|11) ',reason:/registration-replaced|r2 must stay registered|r2 runtime must survive|Expected "actual" to be strictly unequal/},
  {id:'M31-unregister-marks-stopping-in-later-step',file:'src/manager.js',from:"try { pending.push((await this.#stopStep(i.id,true,i.principalId)).task); }",to:"try { pending.push(this.stop(i.id,{confirm:true},i.principalId)); } /* MUTATION: stopping is persisted in a later queue step */",test:'tests/app-package-lifecycle.test.mjs',pattern:'^AH-PK12 ',reason:/INSTANCE_STOPPING/},
  {id:'M32-open-adopts-definition-of-stopping-instance',file:'src/manager.js',from:"      requireCondition(instance.status !== 'stopping','INSTANCE_STOPPING','Instance is stopping; retry after the stopped event.');\n      // App upgrades",to:"      /* MUTATION: stopping is checked only after definition adoption */\n      // App upgrades",test:'tests/app-package-lifecycle.test.mjs',pattern:'^AH-PK12 ',reason:/INSTANCE_STOPPING/},
  {id:'M29-unregister-stops-other-apps',file:'src/manager.js',from:".filter(i => i.appId === appId && (!isTerminal(i.status) || this.#controls.has(i.id)));",to:".filter(i => (!isTerminal(i.status) || this.#controls.has(i.id))); /* MUTATION: unregister stops every app */",test:'tests/app-package-lifecycle.test.mjs',pattern:'^AH-PK09 ',reason:/B must survive|Expected values to be strictly/},
];
const run=(cwd,c)=>{
  const result=spawnSync(process.execPath,['--test','--test-reporter=tap',`--test-name-pattern=${c.pattern}`,c.test],{cwd,encoding:'utf8',timeout:15_000,maxBuffer:2*1024*1024});
  if(result.error)throw result.error;return{code:result.status,log:result.stdout+result.stderr};
};
const results=[];
for(const c of cases){
  const baseline=run(root,c);await writeFile(join(out,c.id+'-baseline.tap'),baseline.log);
  if(baseline.code!==0)throw new Error(`${c.id}: baseline must pass before applying a mutation.`);
  const temp=await mkdtemp(join(tmpdir(),'hm-app-host-mutation-'));
  try{
    for(const path of ['src','tests','scripts','consistency.json','package.json'])await cp(join(root,path),join(temp,path),{recursive:true});
    // Installed dependencies only (the DSH plugin entry imports schemastery/zod/storage-domain); never another repo's source.
    await symlink(join(root,'node_modules'),join(temp,'node_modules'),'dir');
    const target=join(temp,c.file),source=await readFile(target,'utf8');
    if(source.split(c.from).length!==2)throw new Error(`${c.id}: expected exactly one mutation anchor.`);
    const changed=source.replace(c.from,c.to);await writeFile(target,changed);
    const result=run(temp,c);await writeFile(join(out,c.id+'-mutant.tap'),result.log);
    // `failed`: the targeted test fails and the stated reason appears in its log.
    // `killed`: additionally the targeted test reports an assertion failure (`code: 'ERR_ASSERTION'` in its TAP block).
    // Only `killed` is a detection and only `killed` passes the gate; a raw error / generic ERR_TEST_FAILURE is reported, never counted.
    const failed=result.code!==0&&/^not ok /m.test(result.log)&&c.reason.test(result.log),killed=failed&&/^\s+code: 'ERR_ASSERTION'$/m.test(result.log);
    results.push({id:c.id,test:c.test,pattern:c.pattern,baselineExit:baseline.code,mutantExit:result.code,failed,killed,
      originalSourceSha256:createHash('sha256').update(source).digest('hex'),mutatedSourceSha256:createHash('sha256').update(changed).digest('hex')});
    console.log(`${c.id}: baseline PASS; mutation ${killed?'DETECTED (ERR_ASSERTION)':failed?'FAILED WITHOUT ERR_ASSERTION (not counted)':'NOT DETECTED'}`);
  }finally{await rm(temp,{recursive:true,force:true});}
}
await writeFile(join(out,'results.json'),JSON.stringify({generatedAt:new Date().toISOString(),results},null,2)+'\n');
const uncounted=results.filter(r=>r.failed&&!r.killed).map(r=>r.id),survived=results.filter(r=>!r.failed).map(r=>r.id);
const detected=results.length-uncounted.length-survived.length;
if(uncounted.length||survived.length){
  console.error(`Mutation guard FAIL: ${detected}/${results.length} detected by ERR_ASSERTION`+
    (uncounted.length?`; not counted (targeted test fails without ERR_ASSERTION): ${uncounted.join(', ')}`:'')+
    (survived.length?`; not detected: ${survived.join(', ')}`:'')+'.');
  process.exitCode=1;
}else console.log(`Mutation guard PASS: ${detected}/${results.length} mutations detected by ERR_ASSERTION in their targeted test.`);
